### PR TITLE
Upperbound PHP version

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Similar to brick/math#37.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
https://travis-ci.org/github/brick/std/builds/671322721

**Comment by BenMorel** [comment]
👍 

Do you have any idea why Travis doesn't trigger today?

**Comment by GrahamCampbell** [comment]
Because it is using the legacy integration that is now finally dropped by GitHub. You should be able to switch to the new version at https://travis-ci.com/organizations/brick/migrate.

**Comment by GrahamCampbell** [comment]
(if that link is a 404, check the org shows in https://github.com/settings/connections/applications/88c5b97de2dbfc50f3ac)

**Pull request merged**
